name: routine_ade
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  image_picker: ^0.8.7
  image: ^3.0.1
  permission_handler: ^10.2.0

  #추가한 패키지
  flutter_calendar_week: ^3.0.1
  intl: ^0.18.0

  cupertino_icons: ^1.0.6
  json_annotation: ^4.0.1
  shelf_swagger_ui: ^1.0.0+2
  http: ^0.13.3
  http_parser: ^4.0.0
  mime: ^1.0.0
  shared_preferences: ^2.0.8
  table_calendar: ^3.0.0
  fl_chart: ^0.69.0
  kakao_flutter_sdk: ^1.1.0 #카카오로그인
  url_launcher: ^6.0.20 # 카카오 로그인
  webview_flutter: ^3.0.4
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tap-bar/
    - assets/images/emotion/
    - assets/images/new-icons/

fonts:
  - family: NotoSansKR
    fonts:
      - asset: assets/fonts/NotoSansKR-Regular.otf
      - asset: assets/fonts/NotoSansKR-Bold.otf
      - asset: assets/fonts/NotoSansKR-Medium.otf
